version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Build step: no actual build needed for static site

  post_build:
    commands:
      - echo Zipping application for Elastic Beanstalk...
      - zip -r static-site.zip * .[^.]*
      - echo Build completed on `date`

artifacts:
  files:
    - static-site.zip
