version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install  # or pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - npm run build  # only if needed
artifacts:
  files:
    - '**/*'
